### ISSUE TITLE
Subject-level metadata is missing

### ISSUE THREAD

**Issue by fedorov** [eliskape/Radiomics-Atlas#1]
The manuscript where this data is presented (https://link.springer.com/article/10.1007/s10278-024-01028-7) mentions age and sex of subjects included in the study, but I cannot find this information at the subject level in this repository. Would it be possible to include a table with that information?

**Comment by eliskape** [comment]
Thank you for reaching out and for your interest in our study.

We appreciate you pointing out that we could also add detailed information
regarding age and sex of the subjects. Based on your inquiry, we will be
shortly updating the repository to include this additional information of
the subjects at the individual level. This update will help ensure that
patient level data will be available for use together with the radiomics
data presented in our manuscript. This will definitely increase the uses of
our dataset.

We'll keep you informed once the changes are implemented!

Best,
Elisavet

**Comment by fedorov** [comment]
Great news! Thank you for the update.

**Comment by eliskape** [comment]
A table with the subject-level metadata has been now added in the main folder in an Excel (.xlsx) file!
